import type { HelpFeatureGuide } from "./types"

export const featureGuides: HelpFeatureGuide[] = [
  {
    id: "task-launch",
    title: "任务启动",
    purpose: "发起新的短视频生产任务，并确定原始文案、时长、尺寸和所属项目。",
    whenToUse: "当你准备开始一条新内容生产任务时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["负责把原始文案转成需要先审核的任务。", "适合确定本次任务的项目、默认渠道、时长、画幅和启动前风险。"] },
      { title: "页面主要区域", points: ["项目与输出确认", "原始文案和模板", "启动前确认与预算粗估", "最近任务与异常提醒"] },
      { title: "常见操作", points: ["填写任务名称和原始文案", "选择项目、时长和终端尺寸", "查看文案检查和相似任务", "确认提交并固定本次设置"] },
      { title: "常见误区", points: ["不要把技术说明直接写进原始文案", "不要在失败或卡住任务堆积时重复提交同类内容", "不要把提交成功理解成已经完整成片"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery", "task-launch-source-sop"],
  },
  {
    id: "task-review",
    title: "任务审核",
    purpose: "按任务审核 SOP 整条视频查看生成方案、关键画面、画面说明、视频说明和尺寸规格，再决定是否继续生成正片。",
    whenToUse: "当任务进入审核阶段，或方案已通过但还需要继续生成时使用。",
    sections: [
      { title: "何时操作", points: ["任务进入待审核。", "方案待审、已通过待继续、已驳回待处理。"] },
      { title: "点哪里", points: ["在生产看板点「进入任务审核」。", "在任务审核页逐段打开生成方案、关键画面和生成说明。"] },
      { title: "验收什么", points: ["原始文案没有跑偏。", "视频分段连续且终端尺寸正确。", "画面说明和视频说明围绕同一段内容。"] },
      { title: "不要做什么", points: ["不要只看单张图。", "不要把审核通过和继续生成当成同一步。", "不要在方案跑偏时直接继续生成正片。"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery", "failure-triage", "blueprint-review-sop"],
  },
  {
    id: "project-library",
    title: "项目模板库",
    purpose: "查看项目内已经审核通过的生成方案，作为后续复用、对标和稳定风格参考。",
    whenToUse: "当你需要回看某个项目已经通过的方案，或给新任务找参考时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你积累项目级已通过方案。", "帮助你减少每次都从零判断的成本。"] },
      { title: "页面主要区域", points: ["项目选择区", "方案版本列表", "通过时间与来源任务"] },
      { title: "常见操作", points: ["按项目查看已通过方案", "回溯参考任务和版本", "把通过案例当作新任务对照样本"] },
      { title: "常见误区", points: ["不要把模板库当成最终发布文件库", "不要把历史通过方案直接当成所有渠道都通用的固定模板"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery"],
  },
  {
    id: "batch-dashboard",
    title: "生产调度台",
    purpose: "按生产调度 SOP 查看任务状态分组、卡住任务、预计完成时间、最近进展、问题类型和生成服务容量。",
    whenToUse: "当你需要调度当天生产、定位异常任务、判断是否恢复或暂停追加任务时使用。",
    sections: [
      { title: "何时操作", points: ["开班巡检、批量提交后、生成服务容量不足时。", "出现卡住、失败或待审核任务增长时。"] },
      { title: "点哪里", points: ["点侧栏「生产看板」。", "先看排队中、生成中、待审核、卡住、失败、已完成几个生产分组。", "卡住任务点「查看素材文件」，失败任务点「查看失败素材」，待审核任务点「进入任务审核」。"] },
      { title: "验收什么", points: ["排队任务能进入生成中。", "生成中任务有新进展和合理预计时间。", "卡住任务不继续堆积。", "失败任务已完成问题分类并进入素材排查。"] },
      { title: "不要做什么", points: ["不要在看板里直接猜失败原因。", "不要在容量异常时重复提交同一原始文案。", "不要跳过素材排查直接恢复卡住任务。"] },
    ],
    relatedWorkflowIds: ["failure-triage", "production-dispatch-sop", "failed-task-triage-sop", "partial-retry-sop"],
  },
  {
    id: "asset-center",
    title: "素材与交付",
    purpose: "按交付验收 SOP 查看发布文件和中间素材，确认当前任务已经生成了什么、缺什么、能否发布。",
    whenToUse: "当你需要确认任务产出、下载文件或排查交付缺口时使用。",
    sections: [
      { title: "何时操作", points: ["任务已完成后做交付验收。", "失败或卡住任务恢复前先做素材排查。"] },
      { title: "点哪里", points: ["在生产看板点「查看素材文件」或「查看失败素材」。", "进入素材与交付后先看发布文件，再看排查文件列表。"] },
      { title: "验收什么", points: ["成片视频可预览或下载。", "字幕、音频、脚本和时长符合交付要求。", "缺失文件类型已经确认。"] },
      { title: "不要做什么", points: ["不要一上来先翻排查文件。", "不要把下载成功当成内容验收通过。", "不要没确认缺口就连续恢复生成。"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery", "failure-triage", "delivery-acceptance-sop", "partial-retry-sop"],
  },
  {
    id: "model-control-center",
    title: "模型设置",
    purpose: "管理模型接入方、可用模型和默认模型，决定新任务创建时会固定使用哪套生成能力。",
    whenToUse: "当你需要接入新模型、调整默认值或理解模型如何生效时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你维护模型接入配置。", "帮助你理解默认模型如何影响新任务。"] },
      { title: "页面主要区域", points: ["配置概览", "接入方管理", "模型列表", "默认模型"] },
      { title: "四类生成能力", points: ["文本模型负责规划与改写", "图片模型负责关键画面与静态图", "视频模型负责视频生成", "配音接入方负责系统配音"] },
      { title: "常见操作", points: ["新增接入方", "登记模型", "设置全局兜底与新任务默认", "确认新任务会采用哪套默认模型"] },
      { title: "常见误区", points: ["不要把默认模型理解成内容改写开关", "不要把未校验记录当成可用项", "不要把系统理解成旧的双审核流程"] },
    ],
    relatedWorkflowIds: ["model-onboarding-and-defaults"],
  },
  {
    id: "user-center",
    title: "用户中心",
    purpose: "维护内部账号、状态和密码。",
    whenToUse: "当你需要新增或调整运营账号时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["负责内部账号管理。", "帮助你控制谁可以登录后台。"] },
      { title: "页面主要区域", points: ["用户列表", "状态管理", "密码重置"] },
      { title: "常见操作", points: ["新增用户", "启停账号", "重置密码"] },
      { title: "常见误区", points: ["不要把临时账号长期保留", "不要忽略账号状态管理"] },
    ],
    relatedWorkflowIds: [],
  },
]
