import type { HelpFeatureGuide } from "./types"

export const featureGuides: HelpFeatureGuide[] = [
  {
    id: "task-launch",
    title: "任务启动",
    purpose: "发起新的短视频生产任务，并只确定内容母本、时长、尺寸和所属项目。",
    whenToUse: "当你准备开始一条新内容生产任务时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["负责把内容母本转成任务。", "适合确定本次任务的基础方向。"] },
      { title: "页面主要区域", points: ["内容母本配置区", "尺寸与时长约束", "本次任务摘要"] },
      { title: "常见操作", points: ["填写任务名称和内容母本", "选择时长和终端尺寸", "确认所属项目后直接提交"] },
      { title: "常见误区", points: ["不要把技术提示词直接写进内容母本", "不要期待系统替你改题材或换主体"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery"],
  },
  {
    id: "task-review",
    title: "任务审核",
    purpose: "按蓝图审核 SOP 整任务查看蓝图、关键画面、图片提示词、视频提示词和尺寸规格，再决定是否继续完整生成。",
    whenToUse: "当高质量任务进入审核阶段，或蓝图已通过但还需要继续执行时使用。",
    sections: [
      { title: "何时操作", points: ["任务进入 waiting_review lane。", "蓝图待审、已通过待继续、已驳回待处理。"] },
      { title: "点哪里", points: ["在生产调度台点「进入任务审核」。", "在任务审核页逐段打开蓝图、关键画面和提示词。"] },
      { title: "验收什么", points: ["母本语义不跑偏。", "分镜连续且终端尺寸正确。", "图片提示词和视频提示词围绕同一场景契约。"] },
      { title: "不要做什么", points: ["不要只看单张图。", "不要把审核通过和继续执行当成同一步。", "不要在蓝图跑偏时直接继续完整生成。"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery", "failure-triage", "blueprint-review-sop"],
  },
  {
    id: "project-library",
    title: "项目审核库",
    purpose: "查看项目内已经审核通过的蓝图沉淀，作为后续复用、对标和稳定风格基线。",
    whenToUse: "当你需要回看某个项目已经通过的蓝图版本，或给新任务找参考时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你积累项目级已通过蓝图。", "帮助你减少每次都从零判断的成本。"] },
      { title: "页面主要区域", points: ["项目选择区", "蓝图版本列表", "通过时间与来源任务"] },
      { title: "常见操作", points: ["按项目查看已通过蓝图", "回溯参考任务和版本", "把通过案例当作新任务对照样本"] },
      { title: "常见误区", points: ["不要把审核库当成最终交付库", "不要把历史通过蓝图直接当成所有渠道都通用的固定模板"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery"],
  },
  {
    id: "batch-dashboard",
    title: "生产调度台",
    purpose: "按生产调度 SOP 查看任务 lane、卡住任务、ETA、心跳、失败分类、推荐动作和 worker / redis 容量。",
    whenToUse: "当你需要调度当天生产、定位异常任务、判断是否恢复或暂停追加任务时使用。",
    sections: [
      { title: "何时操作", points: ["开班巡检、批量提交后、worker / redis 降级时。", "出现 blocked、failed 或 waiting_review 增长时。"] },
      { title: "点哪里", points: ["点侧栏「生产看板」。", "先看 queued / running / waiting_review / blocked / failed / completed lane。", "blocked 点「打开资产排查」，failed 点「查看失败任务资产」，waiting_review 点「进入任务审核」。"] },
      { title: "验收什么", points: ["queued 能进入 running。", "running 有新心跳和合理 ETA。", "blocked 不继续堆积。", "failed 已完成失败分类并进入资产排查。"] },
      { title: "不要做什么", points: ["不要在看板里直接猜失败原因。", "不要在容量异常时重复提交同一母本。", "不要跳过资产排查直接恢复卡住任务。"] },
    ],
    relatedWorkflowIds: ["failure-triage", "production-dispatch-sop", "failed-task-triage-sop", "partial-retry-sop"],
  },
  {
    id: "asset-center",
    title: "交付资产",
    purpose: "按交付验收 SOP 查看最终交付物和中间产物，确认当前任务已经生成了什么、缺什么、能否交付。",
    whenToUse: "当你需要确认任务产物、下载资产或排查交付缺口时使用。",
    sections: [
      { title: "何时操作", points: ["任务 completed 后做交付验收。", "failed / blocked 恢复前先做资产排查。"] },
      { title: "点哪里", points: ["在生产调度台点「打开任务资产」「查看失败任务资产」或「打开资产排查」。", "进入资产中心后先看最终交付物，再看中间资产列表。"] },
      { title: "验收什么", points: ["最终视频可预览或下载。", "字幕、音频、脚本和时长符合交付要求。", "缺失资产类型已经确认。"] },
      { title: "不要做什么", points: ["不要一上来先翻中间资产。", "不要把下载成功当成内容验收通过。", "不要没确认缺口就连续恢复运行。"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery", "failure-triage", "delivery-acceptance-sop", "partial-retry-sop"],
  },
  {
    id: "model-control-center",
    title: "模型控制中心",
    purpose: "管理 Provider、Model 和默认值基线规则，决定新任务创建时会冻结哪套运行时能力。",
    whenToUse: "当你需要接入新模型、调整默认值或理解模型如何生效时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你维护模型接入链路。", "帮助你理解默认值如何影响任务。"] },
      { title: "页面主要区域", points: ["总览", "Provider 管理", "Model Registry", "Defaults Center"] },
      { title: "四个运行时槽位", points: ["文本模型负责规划与改写", "图片模型负责关键帧与静态图", "视频模型负责视频生成", "TTS Provider 负责配音"] },
      { title: "常见操作", points: ["新增 Provider", "登记 Model", "设置全局默认与任务创建默认值", "确认冻结快照会采用哪套默认值"] },
      { title: "常见误区", points: ["不要把默认值治理理解成内容改写开关", "不要把未校验记录当成可用项", "不要把系统理解成旧分镜/旧关键帧双审核链"] },
    ],
    relatedWorkflowIds: ["model-onboarding-and-defaults"],
  },
  {
    id: "user-center",
    title: "用户中心",
    purpose: "维护内部账号、状态和密码。",
    whenToUse: "当你需要新增或调整运营账号时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["负责内部账号管理。", "帮助你控制谁可以登录后台。"] },
      { title: "页面主要区域", points: ["用户列表", "状态管理", "密码重置"] },
      { title: "常见操作", points: ["新增用户", "启停账号", "重置密码"] },
      { title: "常见误区", points: ["不要把临时账号长期保留", "不要忽略账号状态管理"] },
    ],
    relatedWorkflowIds: [],
  },
]
