import type { HelpFeatureGuide } from "./types"

export const featureGuides: HelpFeatureGuide[] = [
  {
    id: "task-launch",
    title: "任务启动",
    purpose: "发起新的短视频生产任务，并只确定内容母本、时长、尺寸和所属项目。",
    whenToUse: "当你准备开始一条新内容生产任务时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["负责把内容母本转成任务。", "适合确定本次任务的基础方向。"] },
      { title: "页面主要区域", points: ["内容母本配置区", "尺寸与时长约束", "本次任务摘要"] },
      { title: "常见操作", points: ["填写任务名称和内容母本", "选择时长和终端尺寸", "确认所属项目后直接提交"] },
      { title: "常见误区", points: ["不要把技术提示词直接写进内容母本", "不要期待系统替你改题材或换主体"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery"],
  },
  {
    id: "task-review",
    title: "任务审核",
    purpose: "整任务查看蓝图、关键画面、图片提示词、视频提示词和尺寸规格，再决定是否继续完整生成。",
    whenToUse: "当高质量任务进入审核阶段，或蓝图已通过但还需要继续执行时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你一次性判断整套分镜契约是否可用。", "帮助你核对关键画面、旁白、图片提示词和视频提示词是否一致。"] },
      { title: "页面主要区域", points: ["蓝图总览", "场景契约列表", "审核动作与继续执行入口"] },
      { title: "常见操作", points: ["逐段查看关键画面和提示词", "整体判断蓝图是否可继续执行", "审核通过后继续完整视频生成"] },
      { title: "常见误区", points: ["不要只看单张图，要看整套分镜契约是否连续", "不要把审核通过和继续执行当成同一步，审核后仍要显式继续生成"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery", "failure-triage"],
  },
  {
    id: "project-library",
    title: "项目审核库",
    purpose: "查看项目内已经审核通过的蓝图沉淀，作为后续复用、对标和稳定风格基线。",
    whenToUse: "当你需要回看某个项目已经通过的蓝图版本，或给新任务找参考时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你积累项目级已通过蓝图。", "帮助你减少每次都从零判断的成本。"] },
      { title: "页面主要区域", points: ["项目选择区", "蓝图版本列表", "通过时间与来源任务"] },
      { title: "常见操作", points: ["按项目查看已通过蓝图", "回溯参考任务和版本", "把通过案例当作新任务对照样本"] },
      { title: "常见误区", points: ["不要把审核库当成最终交付库", "不要把历史通过蓝图直接当成所有渠道都通用的固定模板"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery"],
  },
  {
    id: "batch-dashboard",
    title: "生产看板",
    purpose: "查看任务运行状态、异常和需要继续处理的工作。",
    whenToUse: "当你需要快速定位异常任务或整体查看任务运行状态时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你找到需要继续处理的任务。", "帮助你区分运行中、完成和失败任务。"] },
      { title: "页面主要区域", points: ["任务列表", "状态摘要", "异常入口"] },
      { title: "常见操作", points: ["筛选异常任务", "从看板继续进入任务审核或资产页", "确认运行状态"] },
      { title: "常见误区", points: ["不要在看板里直接猜失败原因", "看板适合定位，不适合替代资产排查"] },
    ],
    relatedWorkflowIds: ["failure-triage"],
  },
  {
    id: "asset-center",
    title: "交付资产",
    purpose: "查看最终交付物和中间产物，确认当前任务已经生成了什么。",
    whenToUse: "当你需要确认任务产物、下载资产或排查交付缺口时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你确认最终视频是否可交付。", "帮助你回查字幕、脚本和中间产物。"] },
      { title: "页面主要区域", points: ["最终交付物区域", "中间资产列表", "预览与下载入口"] },
      { title: "常见操作", points: ["先看最终视频", "再看字幕和脚本", "必要时下载或预览中间文件"] },
      { title: "常见误区", points: ["不要一上来先翻中间资产", "先看最终交付是否已经满足需求"] },
    ],
    relatedWorkflowIds: ["launch-review-delivery", "failure-triage"],
  },
  {
    id: "model-control-center",
    title: "模型控制中心",
    purpose: "管理 Provider、Model 和默认值基线规则，决定新任务创建时会冻结哪套运行时能力。",
    whenToUse: "当你需要接入新模型、调整默认值或理解模型如何生效时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["帮助你维护模型接入链路。", "帮助你理解默认值如何影响任务。"] },
      { title: "页面主要区域", points: ["总览", "Provider 管理", "Model Registry", "Defaults Center"] },
      { title: "四个运行时槽位", points: ["文本模型负责规划与改写", "图片模型负责关键帧与静态图", "视频模型负责视频生成", "TTS Provider 负责配音"] },
      { title: "常见操作", points: ["新增 Provider", "登记 Model", "设置全局默认与模式默认", "确认冻结快照会采用哪套默认值"] },
      { title: "常见误区", points: ["不要把默认值治理理解成内容改写开关", "不要把未校验记录当成可用项", "不要把系统理解成旧分镜/旧关键帧双审核链"] },
    ],
    relatedWorkflowIds: ["model-onboarding-and-defaults"],
  },
  {
    id: "user-center",
    title: "用户中心",
    purpose: "维护内部账号、状态和密码。",
    whenToUse: "当你需要新增或调整运营账号时使用。",
    sections: [
      { title: "这个页面是干什么的", points: ["负责内部账号管理。", "帮助你控制谁可以登录后台。"] },
      { title: "页面主要区域", points: ["用户列表", "状态管理", "密码重置"] },
      { title: "常见操作", points: ["新增用户", "启停账号", "重置密码"] },
      { title: "常见误区", points: ["不要把临时账号长期保留", "不要忽略账号状态管理"] },
    ],
    relatedWorkflowIds: [],
  },
]
